---
# CI_PREV_PIPELINE_STATUS is set wrong on workflow failures
# https://github.com/woodpecker-ci/woodpecker/issues/3343

steps:
  - name: notify fail
    image: debian:stable-backports
    environment:
      STATUS: failure
    commands:
      - apt update && apt install -q2 -y go-sendxmpp/stable-backports ca-certificates
      - bash .woodpecker/notify.sh
    when:
      - event: [ push, manual, cron ]

depends_on:
  - tests

runs_on: [ failure ]
